hours=int(input())
mins=int(input())
secs=int(input())
hours2=int(input())
mins2=int(input())
secs2=int(input())
h_dif=(hours2-hours)*3600
m_dif=(mins2-mins)*60
s_dif=secs2-secs
t_dif=h_dif+m_dif+s_dif
print(t_dif)
